from zmanim_bot.middlewares.i18n import lazy_gettext as _


sunrise = _('Sunrise')
alos = _('Alot ha-shakhar')
sof_zman_tefila_gra = _('Sof zman tfila [AGRO]')
sof_zman_tefila_ma = _('Sof zman tfila [MA]')
misheyakir_10_2 = _('Misheyakir (zman tallit and tfilin)')
sof_zman_shema_gra = _('Sof zman Shemah [AGRO]')
sof_zman_shema_ma = _('Sof zman Shemah [MA]')
chatzos = _('Chatzot')
mincha_ketana = _('Mincha ktanah')
mincha_gedola = _('Mincha gdolah')
plag_mincha = _('Plag mincha')
sunset = _('Shkia (sunset)')
tzeis_8_5_degrees = _('Tzeit ha-kochavim [8.5 degrees]')
tzeis_72_minutes = _('Tzeit ha-kochavim [72 minutes]')
tzeis_42_minutes = _('Tzeit ha-kochavim [42 minutes]')
tzeis_5_95_degrees = _('Tzeit ha-kochavim [5.95 degrees]')
chatzot_laila = _('Chatzot Laila (midnight)')
astronomical_hour_ma = _('Astronomical hour [MA]')
astronomical_hour_gra = _('Astronomical hour [AGRO]')
