from ...middlewares.i18n import lazy_gettext as _


sunrise = _('sunrise')
alos = _('alos')
sof_zman_tefila_gra = _('sof_zman_tefila_gra')
sof_zman_tefila_ma = _('sof_zman_tefila_ma')
talis_ma = _('talis_ma')
sof_zman_shema_gra = _('sof_zman_shema_gra')
sof_zman_shema_ma = _('sof_zman_shema_ma')
chatzos = _('chatzos')
mincha_ketana = _('mincha_ketana')
mincha_gedola = _('mincha_gedola')
plag_mincha = _('plag_mincha')
sunset = _('sunset')
tzeis_8_5_degrees = _('tzeis_8_5_degrees')
tzeis_72_minutes = _('tzeis_72_minutes')
tzeis_42_minutes = _('tzeis_42_minutes')
tzeis_5_95_degrees = _('tzeis_595_degrees')
chatzot_laila = _('chatzot_laila')
astronomical_hour_ma = _('astronomical_hour_ma')
astronomical_hour_gra = _('astronomical_hour_gra')
