"""HTTP API the mini app calls to read and sync the user's bot settings.

Registered under `{WEBHOOK_PATH}/miniapp` — on the webhook server's app in
prod, on a standalone dev server in polling mode (see main.py). Routes are
added directly (NOT via add_subapp: the pinned aiohttp 3.8.6 resolves sub-app
prefixes through `request.url`, which the pinned yarl rejects when the Host
header carries a port) and the CORS middleware scopes itself by path prefix,
so the webhook route is untouched. Auth is stateless: every request carries
the Mini App initData string — or, for the calendar site outside Telegram, a
Login Widget payload — both validated against the bot token (auth.py). CORS
allows only the MINIAPP_URL origin in prod, anything in dev.

  POST /me    {init_data | auth_data}                        -> profile
  POST /sync  {init_data | auth_data,
               location? | cl_offset? | havdala_opinion? | web_prefs?} -> profile
  POST /websync    {key, sig, web_prefs?}                    -> {web_prefs}
  POST /google-key {credential}                              -> {key, sig, email, name, picture}

/websync and /google-key serve calendar-site users with no Telegram account.
They exist because a browser cannot sync with Google Drive in the background:
minting an access token always shows UI and refresh tokens are never issued to
browsers, so a device opening the site once a day would face a popup every
visit. Instead the bot holds the blob. /google-key verifies a Google ID token
once per device and returns a `key` (derived from the account) plus a `sig`
that authenticates it; /websync stores and returns the blob for a key whose
`sig` checks out. No User document is involved (see repository.models.WebSync).

The profile is {language, cl_offset, havdala_opinion, location{lat,lng,name,
elevation} | null, locations[...], web_prefs | null}. `web_prefs` is the
site's full settings snapshot (its serialized sync blob), stored verbatim and
returned as-is — the bot never interprets it, it only bounds its size and
checks it is JSON. Sync mirrors the bot's own location
semantics: matching coordinates re-activate the saved entry; a new place is
appended while under LOCATION_NUMBER_LIMIT. At the limit a new place is NOT
applied — the bot's saved list is user-curated and never overwritten from the
mini app (the app keeps its local choice; the rest of the sync still applies).
"""

import hashlib
import hmac
import html
import io
import json
import re
from datetime import datetime as dt
from typing import Optional
from urllib.parse import urlsplit

from aiogram import types
from aiohttp import web
from pymongo import ReturnDocument
from pymongo.errors import DuplicateKeyError

from zmanim_bot.config import config
from zmanim_bot.exceptions import NoLocationException
from zmanim_bot.middlewares.i18n import i18n_
from zmanim_bot.misc import bot, db_engine, logger, rate_limit_redis
from zmanim_bot.repository._storage import MAX_LOCATION_NAME_SIZE, _get_or_create_user
from zmanim_bot.repository.models import HAVDALA_OPINIONS, Location, User, WebSync
from zmanim_bot.texts.single import buttons, messages
from zmanim_bot.texts.single import zmanim as zmanim_texts

from .auth import validate_init_data, validate_login_widget, verify_google_id_token
from .metrics import track_miniapp_event

CL_OFFSET_MIN = 1
CL_OFFSET_MAX = 120

# The site's settings snapshot is a few KB even with every list maxed out;
# the cap only keeps garbage out of Mongo (site-side cap is the same).
MAX_WEB_PREFS_CHARS = 65536

# Generous cap for relayed export files (multi-page PDF renders run a few MB;
# Telegram bots can send up to 50 MB).
MAX_EXPORT_BYTES = 30 * 1024 * 1024

# Sync keys are generated by the site (128 bits of randomness, hex). Bound the
# shape so a caller cannot use the collection as free-form storage.
WEB_SYNC_KEY_RE = re.compile(r'^[A-Za-z0-9_-]{32,64}$')

# Per-IP budget for the two site endpoints. A real device makes a handful of
# calls per session, so this only bites abuse (a burst of Google-token
# verifications, or hammering the store). Fail-open: a Redis blip must not take
# the endpoints down, and correctness never depends on it — /websync is gated
# by the key signature, not the rate limit. Behind a reverse proxy the client
# IP is the first X-Forwarded-For hop, so the proxy must set/overwrite it.
WEB_SYNC_RATE_LIMIT = 60
WEB_SYNC_RATE_WINDOW = 60


def _client_ip(request: web.Request) -> str:
    # X-Forwarded-For is client-supplied and spoofable unless a trusted proxy
    # overwrites it, so it's used only when TRUST_PROXY_HEADERS says so.
    # Otherwise the direct socket peer, which the caller cannot forge — else a
    # client rotating the header would get a fresh bucket per request and defeat
    # the limit.
    if config.TRUST_PROXY_HEADERS:
        forwarded = request.headers.get('X-Forwarded-For', '')
        first = forwarded.split(',')[0].strip()
        if first:
            return first
    return request.remote or 'unknown'


# INCR + EXPIRE as one atomic step. Doing them as two commands lets a Redis
# disconnect land between them: the key is created without a TTL, never gets
# one (the count is no longer 1 on later calls), and that IP is 429'd forever.
_RATE_LIMIT_LUA = "local c = redis.call('incr', KEYS[1]); if c == 1 then redis.call('expire', KEYS[1], ARGV[1]) end; return c"


async def _enforce_rate_limit(request: web.Request, bucket: str) -> None:
    key = f'miniapp:rl:{bucket}:{_client_ip(request)}'
    try:
        count = await rate_limit_redis.eval(_RATE_LIMIT_LUA, 1, key, WEB_SYNC_RATE_WINDOW)
    except Exception:
        logger.warning('rate-limit check failed for %s; allowing request', bucket, exc_info=True)
        return
    if int(count) > WEB_SYNC_RATE_LIMIT:
        raise web.HTTPTooManyRequests(reason='Too many requests')


async def _json_dict_body(request: web.Request) -> dict:
    """The request body as a dict, or 400. Valid JSON need not be an object —
    `[]`, `null`, `42` all parse — so guard before any `body.get(...)` reaches
    an AttributeError and 500s."""
    try:
        body = await request.json()
    except ValueError:
        raise web.HTTPBadRequest(reason='Invalid JSON body')
    if not isinstance(body, dict):
        raise web.HTTPBadRequest(reason='Body must be a JSON object')
    return body


def _origin_allowed(origin: str) -> bool:
    if not config.IS_PROD:
        return True
    if not config.MINIAPP_URL:
        return False
    allowed = urlsplit(config.MINIAPP_URL)
    got = urlsplit(origin)
    return (got.scheme, got.netloc) == (allowed.scheme, allowed.netloc)


def _make_cors_middleware(prefix: str):
    """CORS + preflight handling for the mini-app routes only; everything
    outside `prefix` (i.e. the Telegram webhook) passes through untouched."""

    @web.middleware
    async def cors_middleware(request: web.Request, handler) -> web.StreamResponse:
        if not request.path.startswith(prefix):
            return await handler(request)

        if request.method == 'OPTIONS':
            response: web.StreamResponse = web.Response(status=204)
        else:
            try:
                response = await handler(request)
            except web.HTTPException as exc:
                response = exc

        origin = request.headers.get('Origin')
        if origin and _origin_allowed(origin):
            response.headers['Access-Control-Allow-Origin'] = origin
            response.headers['Access-Control-Allow-Methods'] = 'POST, OPTIONS'
            response.headers['Access-Control-Allow-Headers'] = 'Content-Type'
            response.headers['Access-Control-Max-Age'] = '3600'
            response.headers.setdefault('Vary', 'Origin')
        return response

    return cors_middleware


async def _user_from_init_data(init_data) -> User:
    """Validate an initData string and return the bot user it belongs to."""
    if not isinstance(init_data, str) or not init_data:
        raise web.HTTPUnauthorized(reason='Missing init_data')

    parsed = validate_init_data(init_data, config.BOT_TOKEN)
    if not parsed or 'user' not in parsed:
        raise web.HTTPUnauthorized(reason='Invalid init_data')

    info = parsed['user']
    tg_user = types.User(
        id=info['id'],
        is_bot=info.get('is_bot', False),
        first_name=info.get('first_name'),
        last_name=info.get('last_name'),
        username=info.get('username'),
        language_code=info.get('language_code'),
    )
    return await _get_or_create_user(tg_user)


async def _user_from_login_widget(auth_data) -> User:
    """Validate a Login Widget payload and return the bot user it belongs to."""
    parsed = validate_login_widget(auth_data, config.BOT_TOKEN) if isinstance(auth_data, dict) else None
    if not parsed:
        raise web.HTTPUnauthorized(reason='Invalid auth_data')
    tg_user = types.User(
        id=parsed['id'],
        is_bot=False,
        first_name=parsed.get('first_name'),
        last_name=parsed.get('last_name'),
        username=parsed.get('username'),
    )
    return await _get_or_create_user(tg_user)


async def _authorize(request: web.Request) -> tuple[User, dict]:
    """Validate a JSON request's credential (Mini App initData, or the site's
    Login Widget payload) and return the bot user + body."""
    try:
        body = await request.json()
    except ValueError:
        raise web.HTTPBadRequest(reason='Invalid JSON body')
    if body.get('auth_data') is not None:
        user = await _user_from_login_widget(body['auth_data'])
    else:
        user = await _user_from_init_data(body.get('init_data'))
    return user, body


def _location_payload(location: Location) -> dict:
    return {
        'lat': location.lat,
        'lng': location.lng,
        'name': location.name,
        'elevation': location.elevation or 0,
    }


def _profile_payload(user: User) -> dict:
    try:
        location = _location_payload(user.location)
    except NoLocationException:
        location = None
    return {
        'language': user.language,
        'cl_offset': user.cl_offset,
        'havdala_opinion': user.havdala_opinion,
        'location': location,
        # The whole saved list, so the mini app can offer them like the bot does.
        'locations': [_location_payload(loc) for loc in user.location_list],
        # The site's settings snapshot, verbatim (opaque to the bot).
        'web_prefs': user.web_prefs,
    }


def _unique_location_name(name: str, locations: list[Location]) -> str:
    """The bot's location UI addresses entries by name, so names must be unique."""
    existing = {loc.name for loc in locations}
    if name not in existing:
        return name
    for i in range(2, 100):
        suffix = f' ({i})'
        candidate = name[: MAX_LOCATION_NAME_SIZE - len(suffix)] + suffix
        if candidate not in existing:
            return candidate
    return name  # 99 clashes: give up on uniqueness rather than fail the sync


def _apply_location(user: User, data) -> bool:
    """Apply a location change; returns False when it can't be (list full)."""
    if not isinstance(data, dict):
        raise web.HTTPBadRequest(reason='location must be an object')
    try:
        lat = float(data['lat'])
        lng = float(data['lng'])
    except (KeyError, TypeError, ValueError):
        raise web.HTTPBadRequest(reason='location.lat/lng must be numbers')
    if not (-90 <= lat <= 90 and -180 <= lng <= 180):
        raise web.HTTPBadRequest(reason='location.lat/lng out of range')

    existing = next((loc for loc in user.location_list if loc.lat == lat and loc.lng == lng), None)
    if existing is None and len(user.location_list) >= config.LOCATION_NUMBER_LIMIT:
        # The saved list is user-curated and at its limit — never replace or
        # evict entries from the mini app. The app keeps its local choice.
        return False

    name = str(data.get('name') or '').strip() or f'{lat:.3f}, {lng:.3f}'
    if len(name) > MAX_LOCATION_NAME_SIZE:
        name = f'{name[:MAX_LOCATION_NAME_SIZE]}...'
    try:
        elevation = max(0, int(data.get('elevation') or 0))
    except (TypeError, ValueError):
        elevation = 0

    for loc in user.location_list:
        loc.is_active = False
    if existing:
        existing.is_active = True
    else:
        name = _unique_location_name(name, user.location_list)
        user.location_list.append(Location(lat=lat, lng=lng, name=name, is_active=True, elevation=elevation))
    return True


def _format_change(label, old, new) -> str:
    """One italic '• Label: old → new' line; without the arrow part when there
    was no previous value (e.g. a first location)."""
    new_text = html.escape(str(new))
    if old is None:
        return f'<i>• {label}: {new_text}</i>'
    return f'<i>• {label}: {html.escape(str(old))} → {new_text}</i>'


async def _notify_settings_changed(user: User, changes: list) -> None:
    """Silent confirmation in the bot chat, so a mini-app change never goes
    unnoticed. Best-effort: a failed send (blocked bot, deleted chat) must not
    fail the sync itself."""
    lines = [f'<i>{messages.miniapp_settings_changed}</i>']
    lines += [_format_change(label, old, new) for label, old, new in changes]
    try:
        await bot.send_message(user.user_id, '\n'.join(lines), disable_notification=True)
    except Exception as e:
        logger.warning('miniapp: could not notify %s about a settings change: %s', user.user_id, e)


def _auth_source(body: dict) -> str:
    """'web' for a Login Widget sign-in (site outside Telegram), else 'miniapp'."""
    return 'web' if body.get('auth_data') is not None else 'miniapp'


async def handle_me(request: web.Request) -> web.Response:
    user, body = await _authorize(request)
    # /me fires once per launch — the "calendar opened" stats event.
    await track_miniapp_event('Mini app opened', user, source=_auth_source(body))
    return web.json_response(_profile_payload(user))


async def handle_sync(request: web.Request) -> web.Response:
    user, body = await _authorize(request)
    # The API runs outside aiogram's handler context, so the lazy gettext
    # strings (labels and values below) need the locale set for this task.
    i18n_.ctx_locale.set(user.language or 'en')

    # (label, old, new) display values for the confirmation message; `old` is
    # None when there was nothing before. No-op writes are saved but not
    # announced (nothing visibly changed).
    changes: list = []
    changed = False
    # Did a *structured* field change (location / cl_offset / havdala)? Those
    # are rare, deliberate edits and go through a full-document save. A
    # web_prefs-only change (the routine background blob sync) does not, so it
    # can't rewrite — and clobber — a structured field a bot handler changed
    # concurrently between this request's load and its write.
    structured_changed = False

    if body.get('location') is not None:
        try:
            old_location = user.location.name
        except NoLocationException:
            old_location = None
        if _apply_location(user, body['location']):
            changed = True
            structured_changed = True
            if user.location.name != old_location:
                changes.append((buttons.sm_location, old_location, user.location.name))

    cl_offset = body.get('cl_offset')
    if cl_offset is not None:
        if not isinstance(cl_offset, int) or not CL_OFFSET_MIN <= cl_offset <= CL_OFFSET_MAX:
            raise web.HTTPBadRequest(reason='cl_offset out of range')
        if cl_offset != user.cl_offset:
            changes.append((
                buttons.sm_candle,
                f'{user.cl_offset} {messages.minutes_short}',
                f'{cl_offset} {messages.minutes_short}',
            ))
        user.cl_offset = cl_offset
        changed = True
        structured_changed = True

    havdala = body.get('havdala_opinion')
    if havdala is not None:
        if havdala not in HAVDALA_OPINIONS:
            raise web.HTTPBadRequest(reason='Unknown havdala_opinion')
        if havdala != user.havdala_opinion:
            changes.append((
                buttons.sm_havdala,
                # A stored opinion should always have a display name; fall back
                # to the raw key rather than crash the sync if it ever doesn't.
                getattr(zmanim_texts, user.havdala_opinion, user.havdala_opinion),
                getattr(zmanim_texts, havdala),
            ))
        user.havdala_opinion = havdala
        changed = True
        structured_changed = True

    web_prefs = body.get('web_prefs')
    if web_prefs is not None:
        # Stored verbatim, never interpreted; only bounded and JSON-checked.
        # Blob updates are routine background syncs — no chat notification.
        if not isinstance(web_prefs, str) or len(web_prefs) > MAX_WEB_PREFS_CHARS:
            raise web.HTTPBadRequest(reason='web_prefs must be a string under the size cap')
        try:
            json.loads(web_prefs)
        except ValueError:
            raise web.HTTPBadRequest(reason='web_prefs must be valid JSON')
        if web_prefs != user.web_prefs:
            user.web_prefs = web_prefs
            changed = True

    if changed:
        if structured_changed:
            await db_engine.save(user)
        else:
            # web_prefs-only: write just that field, so a routine blob sync
            # can't overwrite structured fields with the copy it loaded.
            await db_engine.get_collection(User).update_one(
                {'user_id': user.user_id}, {'$set': {'web_prefs': user.web_prefs}}
            )
        fields = [key for key in ('location', 'cl_offset', 'havdala_opinion', 'web_prefs') if body.get(key) is not None]
        await track_miniapp_event('Mini app settings sync', user, fields=fields, source=_auth_source(body))
    if changes:
        await _notify_settings_changed(user, changes)
    return web.json_response(_profile_payload(user))


async def handle_export(request: web.Request) -> web.Response:
    """Relay an export file to the user's chat — the Telegram webview can't
    download files, so the mini app posts them here (multipart: init_data
    field + file part) and the bot delivers as a document."""
    if not (request.content_type or '').startswith('multipart/'):
        raise web.HTTPBadRequest(reason='multipart/form-data expected')

    init_data = None
    filename = None
    content = None
    reader = await request.multipart()
    async for part in reader:
        if part.name == 'init_data':
            init_data = (await part.read(decode=True)).decode('utf-8', 'replace')
        elif part.name == 'file':
            filename = (part.filename or 'export').rsplit('/', 1)[-1][:120]
            # Stream with a size cap — client_max_size doesn't govern multipart.
            chunks = []
            size = 0
            while True:
                chunk = await part.read_chunk(64 * 1024)
                if not chunk:
                    break
                size += len(chunk)
                if size > MAX_EXPORT_BYTES:
                    raise web.HTTPRequestEntityTooLarge(max_size=MAX_EXPORT_BYTES, actual_size=size)
                chunks.append(chunk)
            content = b''.join(chunks)

    user = await _user_from_init_data(init_data)
    if not content or not filename:
        raise web.HTTPBadRequest(reason='Missing file')

    try:
        await bot.send_document(user.user_id, types.InputFile(io.BytesIO(content), filename=filename))
    except Exception as e:
        logger.warning('miniapp: could not deliver export %r to %s: %s', filename, user.user_id, e)
        raise web.HTTPBadGateway(reason='Could not deliver the file')
    await track_miniapp_event('Mini app export', user, filename=filename)
    return web.json_response({'ok': True})


def _web_sync_key(body: dict) -> str:
    """The sync key from a request body, or 400."""
    key = body.get('key')
    if not isinstance(key, str) or not WEB_SYNC_KEY_RE.match(key):
        raise web.HTTPBadRequest(reason='Invalid key')
    return key


def _validated_blob(body: dict) -> Optional[str]:
    """The blob to store, or None when the request is a read. Same bounds as
    `web_prefs` on /sync: the bot stores it verbatim and never reads into it."""
    blob = body.get('web_prefs')
    if blob is None:
        return None
    if not isinstance(blob, str) or len(blob) > MAX_WEB_PREFS_CHARS:
        raise web.HTTPBadRequest(reason='web_prefs must be a string under the size cap')
    try:
        json.loads(blob)
    except ValueError:
        raise web.HTTPBadRequest(reason='web_prefs must be valid JSON')
    return blob


def websync_signature(key: str) -> str:
    """A MAC proving this key was issued by us.

    The server cannot re-derive a `key` from a request alone (that needs the
    Google `sub`), so it cannot tell an issued key from a random string — which
    is what let any caller create rows. This signature closes that: it is
    HMAC(bot token, key), so the server recomputes it from the key alone and
    accepts only keys it minted, while a caller who doesn't hold the bot token
    cannot forge one for a key they invented. Handed to the device beside its
    key by /google-key.
    """
    return hmac.new(config.BOT_TOKEN.encode(), f'websync:{key}'.encode(), hashlib.sha256).hexdigest()


async def _upsert_blob(collection, key: str, blob: str) -> Optional[dict]:
    """Store `blob` under `key` atomically, returning the stored row.

    A single upsert, so two devices first-writing the same key concurrently
    can't both insert (the read-then-insert this replaced let the second raise
    DuplicateKeyError → 500). On the rare server-side upsert race that still
    surfaces a duplicate, retry once — the row now exists, so it updates.
    """
    update = {'$set': {'blob': blob, 'updated_at': dt.utcnow()}}
    for attempt in range(2):
        try:
            return await collection.find_one_and_update(
                {'key': key}, update, upsert=True, return_document=ReturnDocument.AFTER,
            )
        except DuplicateKeyError:
            if attempt:
                raise
    return None


async def handle_web_sync(request: web.Request) -> web.Response:
    """Read and write the settings blob of a site user with no Telegram account.

    There is no Telegram account and no session here — the credential is the
    `key` the site got from /google-key plus its `sig` (see websync_signature).
    The signature is what makes this safe to expose: without it any caller
    could create rows under invented keys and grow the collection without
    bound. Sending `web_prefs` stores it; omitting it is a plain read. One
    round trip both pushes and pulls.
    """
    body = await _json_dict_body(request)

    await _enforce_rate_limit(request, 'websync')

    key = _web_sync_key(body)
    sig = body.get('sig')
    if not isinstance(sig, str) or not hmac.compare_digest(sig, websync_signature(key)):
        raise web.HTTPUnauthorized(reason='Invalid key signature')

    blob = _validated_blob(body)
    collection = db_engine.get_collection(WebSync)
    if blob is not None:
        record = await _upsert_blob(collection, key, blob)
    else:
        # A read still refreshes the TTL: a device whose settings already match
        # the remote only ever reads, and without this its row would be reaped
        # mid-use, losing the only remote copy. upsert=False so a read never
        # creates a row.
        record = await collection.find_one_and_update(
            {'key': key}, {'$currentDate': {'updated_at': True}}, return_document=ReturnDocument.AFTER,
        )

    return web.json_response({'web_prefs': record['blob'] if record else None})


def google_sync_key(sub: str) -> str:
    """The sync key for a Google account.

    HMAC of the account's stable `sub` under the bot token: deterministic, so
    every device signing into the same Google account lands on the same blob,
    and unguessable without the bot token, so knowing someone's Google id does
    not reveal their key. It never leaves this server except to the signed-in
    device itself, and the Google id is never stored.

    Tied to BOT_TOKEN: rotating that orphans existing blobs (users re-sync
    rather than lose settings, since the device still holds its own copy).
    """
    digest = hmac.new(config.BOT_TOKEN.encode(), f'google-sync:{sub}'.encode(), hashlib.sha256)
    return digest.hexdigest()[:32]


async def handle_google_key(request: web.Request) -> web.Response:
    """Exchange a Google ID token for that account's sync key and signature.

    Runs once per device: afterwards the site keeps the key + signature and
    syncs through /websync without ever contacting Google again. That is the
    whole point — a browser cannot renew a Google access token without showing
    UI, so any design that needs one on page load makes a daily visitor face a
    popup. The signature authenticates every later /websync call, so the store
    can be public without letting anyone create rows.

    The profile fields come back too so the site can show who is signed in
    without a second Google call.
    """
    body = await _json_dict_body(request)

    await _enforce_rate_limit(request, 'google-key')

    claims = await verify_google_id_token(body.get('credential'), config.GOOGLE_CLIENT_ID)
    if not claims:
        raise web.HTTPUnauthorized(reason='Invalid Google credential')

    key = google_sync_key(claims['sub'])
    return web.json_response({
        'key': key,
        'sig': websync_signature(key),
        'email': claims.get('email'),
        'name': claims.get('name'),
        'picture': claims.get('picture'),
    })


def register_miniapp_api(app: web.Application, prefix: str) -> None:
    """Add the mini-app API (routes + scoped CORS) to an existing app."""
    app.middlewares.append(_make_cors_middleware(prefix))
    app.router.add_post(f'{prefix}/me', handle_me)
    app.router.add_post(f'{prefix}/sync', handle_sync)
    app.router.add_post(f'{prefix}/export', handle_export)
    app.router.add_post(f'{prefix}/websync', handle_web_sync)
    app.router.add_post(f'{prefix}/google-key', handle_google_key)
