name: Zmanim bot beta CI

on:
  push:
    branches:
      - beta
#   pull_request:
#     branches:
#       - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t zmanim-bot -f Dockerfile .
      - name: Tags
        run: |
          docker tag zmanim-bot ${{ secrets.DOCKER_USER }}/zmanim-bot:${{ github.sha }}
          docker tag zmanim-bot ${{ secrets.DOCKER_USER }}/zmanim-bot:beta
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/zmanim-bot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/zmanim-bot:beta
